// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    id, created_at, updated_at, title, body 
) VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2
) RETURNING id, created_at, updated_at, title, body
`

type CreateNoteParams struct {
	Title string
	Body  sql.NullString
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Body,
	)
	return i, err
}
